const specificationsByCategory = {
  mobiles: {
    screenSize: "Kích thước màn hình",
    resolution: "Độ phân giải",
    battery: "Dung lượng pin",
    camera: "Thông số camera",
    processor: "Bộ vi xử lý",
    ram: "Dung lượng RAM",
    storage: "Dung lượng lưu trữ",
    os: "Hệ điều hành",
    connectivity: "Kết nối",
    weight: "Khối lượng",
  },
  laptop: {
    screenSize: "Kích thước màn hình",
    resolution: "Độ phân giải",
    processor: "Bộ vi xử lý",
    ram: "Dung lượng RAM",
    storage: "Dung lượng lưu trữ",
    graphicsCard: "Card đồ họa",
    battery: "Dung lượng pin",
    os: "Hệ điều hành",
    weight: "Khối lượng",
    connectivity: "Kết nối",
    usbPorts: "Số cổng USB",
    hasTouchscreen: "Màn hình cảm ứng",
  },
  ipad: {
    screenSize: "Kích thước màn hình",
    resolution: "Độ phân giải",
    battery: "Dung lượng pin",
    camera: "Thông số camera",
    processor: "Bộ vi xử lý",
    ram: "Dung lượng RAM",
    storage: "Dung lượng lưu trữ",
    os: "Hệ điều hành",
    connectivity: "Kết nối",
    weight: "Khối lượng",
    hasStylusSupport: "Hỗ trợ bút cảm ứng",
  },
  watches: {
    screenSize: "Kích thước màn hình",
    resolution: "Độ phân giải",
    battery: "Dung lượng pin",
    os: "Hệ điều hành",
    connectivity: "Kết nối",
    weight: "Khối lượng",
    waterResistance: "Khả năng chống nước",
    sensors: "Cảm biến",
    strapMaterial: "Chất liệu dây",
    isFitnessTracker: "Theo dõi sức khỏe",
  },
  // televisions: {
  //   screenSize: "Kích thước màn hình",
  //   weight: "Khối lượng",
  //   refreshRate: "Tần số quét",
  //   imageTechnology: "Công nghệ hình ảnh",
  //   os: "Hệ điều hành",
  // },
  accessory: {
    compatibility: "Tương thích với thiết bị",
    material: "Chất liệu",
    colorOptions: "Các tùy chọn màu sắc",
    weight: "Khối lượng",
    dimensions: "Kích thước",
    isWireless: "Không dây",
    batteryLife: "Thời gian pin",
  },
};

export default specificationsByCategory;
